export const FETCH_WELCOME_DATA = 'example/FETCH_WELCOME_DATA';
export const FETCH_WELCOME_DATA_SUCCESS = 'example/FETCH_WELCOME_DATA_SUCCESS';
export const FETCH_WELCOME_DATA_ERROR = 'example/FETCH_WELCOME_DATA_ERROR';
